table f_campanas
	lineageTag: 26a9e9b1-169e-4e51-8a15-071f4cdc81a3

	column ID
		dataType: string
		lineageTag: 311c4b9e-e95c-41b6-95bd-9f1821d65751
		summarizeBy: none
		sourceColumn: ID

		annotation SummarizationSetBy = Automatic

	column Año_Nacimiento
		dataType: int64
		formatString: 0
		lineageTag: ad635b85-9aee-44cd-99e6-1117f77709d4
		summarizeBy: sum
		sourceColumn: Año_Nacimiento

		annotation SummarizationSetBy = Automatic

	column Edad
		dataType: string
		lineageTag: e1c7d088-deba-4086-9865-58a41f45a528
		summarizeBy: none
		sourceColumn: Edad

		annotation SummarizationSetBy = Automatic

	column Educación
		dataType: string
		lineageTag: beb903f6-3814-44fe-aa08-a3d42280eeb6
		summarizeBy: none
		sourceColumn: Educación

		annotation SummarizationSetBy = Automatic

	column Estado_Civil
		dataType: string
		lineageTag: ab258274-09d0-4600-80e4-0000dec835f6
		summarizeBy: none
		sourceColumn: Estado_Civil

		annotation SummarizationSetBy = Automatic

	column Ingreso_Familiar
		dataType: decimal
		formatString: #,0.###############\ "€";-#,0.###############\ "€";#,0.###############\ "€"
		lineageTag: f5cdbf48-d098-427a-b25c-837384b7293e
		summarizeBy: sum
		sourceColumn: Ingreso_Familiar

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"es-ES"}

	column Hijos_Pequeños
		dataType: string
		lineageTag: 30d12b5f-6084-4da3-97ba-0a72eb332915
		summarizeBy: none
		sourceColumn: Hijos_Pequeños

		annotation SummarizationSetBy = Automatic

	column Hijos_Adolescentes
		dataType: string
		lineageTag: 70435cb9-4261-4a52-b9cc-1222713ab8fa
		summarizeBy: none
		sourceColumn: Hijos_Adolescentes

		annotation SummarizationSetBy = Automatic

	column Fecha_Alta
		dataType: dateTime
		formatString: Long Date
		lineageTag: 936a74a3-f847-438e-9f9d-fc1563926fff
		summarizeBy: none
		sourceColumn: Fecha_Alta

		variation Variación
			isDefault
			relationship: 84b2a15f-963c-4cc0-b8fd-e9c7f9267c20
			defaultHierarchy: LocalDateTable_08fc6284-1eb8-4588-92ea-7ea5bf2c8b99.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Recencia
		dataType: int64
		formatString: 0
		lineageTag: b716fcf7-6709-4538-946c-5d82e833b760
		summarizeBy: sum
		sourceColumn: Recencia

		annotation SummarizationSetBy = Automatic

	column Gasto_Vinos
		dataType: decimal
		formatString: #,0.###############\ "€";-#,0.###############\ "€";#,0.###############\ "€"
		lineageTag: d3de2657-eaf2-4999-9520-d2039944f7e2
		summarizeBy: sum
		sourceColumn: Gasto_Vinos

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"es-ES"}

	column Gasto_Frutas
		dataType: decimal
		formatString: #,0.###############\ "€";-#,0.###############\ "€";#,0.###############\ "€"
		lineageTag: 63cadb23-cb08-4f04-835c-d4c65b3d9a59
		summarizeBy: sum
		sourceColumn: Gasto_Frutas

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"es-ES"}

	column Gasto_Carne
		dataType: decimal
		formatString: #,0.###############\ "€";-#,0.###############\ "€";#,0.###############\ "€"
		lineageTag: fb0abf7e-600b-4662-b17c-298951f69c27
		summarizeBy: sum
		sourceColumn: Gasto_Carne

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"es-ES"}

	column Gasto_Pescado
		dataType: decimal
		formatString: #,0.###############\ "€";-#,0.###############\ "€";#,0.###############\ "€"
		lineageTag: d82dceb9-7b61-4e4e-9d73-82165179e34f
		summarizeBy: sum
		sourceColumn: Gasto_Pescado

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"es-ES"}

	column Gasto_Dulces
		dataType: decimal
		formatString: #,0.###############\ "€";-#,0.###############\ "€";#,0.###############\ "€"
		lineageTag: 1b4ee1ac-842d-4188-9da8-79876b5f118e
		summarizeBy: sum
		sourceColumn: Gasto_Dulces

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"es-ES"}

	column Gasto_Producto_Premium
		dataType: decimal
		formatString: #,0.###############\ "€";-#,0.###############\ "€";#,0.###############\ "€"
		lineageTag: eb700bf1-8922-42d7-99cd-ce5b51016477
		summarizeBy: sum
		sourceColumn: Gasto_Producto_Premium

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"es-ES"}

	column Compras_Descuento
		dataType: int64
		formatString: 0
		lineageTag: 3d784206-0329-4f61-a6db-dd06943fb65c
		summarizeBy: sum
		sourceColumn: Compras_Descuento

		annotation SummarizationSetBy = Automatic

	column Compras_Web
		dataType: int64
		formatString: 0
		lineageTag: 52dc264e-3546-4346-afe0-4283aa8f68c7
		summarizeBy: sum
		sourceColumn: Compras_Web

		annotation SummarizationSetBy = Automatic

	column Compras_Catalogo
		dataType: int64
		formatString: 0
		lineageTag: 8e4c85d9-5c83-46c4-9063-c6e7810ceb2a
		summarizeBy: sum
		sourceColumn: Compras_Catalogo

		annotation SummarizationSetBy = Automatic

	column Compras_Tienda
		dataType: int64
		formatString: 0
		lineageTag: 91088e12-2979-4342-a6ed-14724375836e
		summarizeBy: sum
		sourceColumn: Compras_Tienda

		annotation SummarizationSetBy = Automatic

	column Visitas_Web_Mes
		dataType: int64
		formatString: 0
		lineageTag: d2afdf46-f232-4ecf-95a0-ce2162a7a82e
		summarizeBy: sum
		sourceColumn: Visitas_Web_Mes

		annotation SummarizationSetBy = Automatic

	column Campaña_Aceptada_3
		dataType: string
		lineageTag: d48ad181-8372-4c69-91fb-4c1701b6dc0b
		summarizeBy: none
		sourceColumn: Campaña_Aceptada_3

		annotation SummarizationSetBy = Automatic

	column Campaña_Aceptada_4
		dataType: string
		lineageTag: be677f9e-1432-4bc3-9ce3-b32a2cea0c10
		summarizeBy: none
		sourceColumn: Campaña_Aceptada_4

		annotation SummarizationSetBy = Automatic

	column Campaña_Aceptada_5
		dataType: string
		lineageTag: 54a0f699-de48-4eef-9be5-de2dda0d478c
		summarizeBy: none
		sourceColumn: Campaña_Aceptada_5

		annotation SummarizationSetBy = Automatic

	column Campaña_Aceptada_1
		dataType: string
		lineageTag: 4a9ba785-4335-4d69-93e3-ea76737f8dbf
		summarizeBy: none
		sourceColumn: Campaña_Aceptada_1

		annotation SummarizationSetBy = Automatic

	column Campaña_Aceptada_2
		dataType: string
		lineageTag: 75143aec-9871-4a5c-b3ef-e932537f80bd
		summarizeBy: none
		sourceColumn: Campaña_Aceptada_2

		annotation SummarizationSetBy = Automatic

	column Queja
		dataType: string
		lineageTag: 51f7dec1-3d37-4eab-a0d9-cde079ee40d1
		summarizeBy: none
		sourceColumn: Queja

		annotation SummarizationSetBy = Automatic

	column Costo_Contacto
		dataType: decimal
		formatString: #,0.###############\ "€";-#,0.###############\ "€";#,0.###############\ "€"
		lineageTag: f02c6f38-0652-4eac-aafe-5a93e591c764
		summarizeBy: sum
		sourceColumn: Costo_Contacto

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"es-ES"}

	column Ganancias_Campaña
		dataType: decimal
		formatString: #,0.###############\ "€";-#,0.###############\ "€";#,0.###############\ "€"
		lineageTag: 27ef7c9a-bb0b-4af6-bf76-8eeae66f2aba
		summarizeBy: sum
		sourceColumn: Ganancias_Campaña

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"es-ES"}

	column Respuesta_Campaña
		dataType: string
		lineageTag: 3d8f7e2c-c31e-4898-94b4-8514524c1e1c
		summarizeBy: none
		sourceColumn: Respuesta_Campaña

		annotation SummarizationSetBy = Automatic

	column Origen_Compra
		dataType: string
		lineageTag: 654fbd9b-b4d5-430a-b7e8-bd975fc23f33
		summarizeBy: none
		sourceColumn: Origen_Compra

		annotation SummarizationSetBy = Automatic

	partition f_campanas = m
		mode: import
		queryGroup: Hechos
		source = ```
				let
				    Origen = Csv.Document(Web.Contents("https://raw.githubusercontent.com/ea-analisisdatos/powerbi/main/data/marketing_campaign.csv"),[Delimiter=";", Columns=29, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"Encabezados promovidos" = Table.PromoteHeaders(Origen, [PromoteAllScalars=true]),
				    #"Tipo cambiado" = Table.TransformColumnTypes(#"Encabezados promovidos",{{"Year_Birth", Int64.Type}, 
				                                                                            {"Income", Currency.Type}, 
				                                                                            {"Dt_Customer", type date}, 
				                                                                            {"Recency", Int64.Type}, 
				                                                                            {"MntWines", Currency.Type}, 
				                                                                            {"MntFruits", Currency.Type}, 
				                                                                            {"MntMeatProducts", Currency.Type}, 
				                                                                            {"MntFishProducts", Currency.Type}, 
				                                                                            {"MntSweetProducts", Currency.Type}, 
				                                                                            {"MntGoldProds", Currency.Type}, 
				                                                                            {"NumDealsPurchases", Int64.Type}, 
				                                                                            {"NumWebPurchases", Int64.Type}, 
				                                                                            {"NumCatalogPurchases", Int64.Type}, 
				                                                                            {"NumStorePurchases", Int64.Type}, 
				                                                                            {"NumWebVisitsMonth", Int64.Type}, 
				                                                                            {"Z_CostContact", Currency.Type}, 
				                                                                            {"Z_Revenue", Currency.Type}}),
				    #"Columnas con nombre cambiado" = Table.RenameColumns(#"Tipo cambiado",{{"Year_Birth", "Año_Nacimiento"}, 
				                                                                            {"Education", "Educación"}, 
				                                                                            {"Marital_Status", "Estado_Civil"}, 
				                                                                            {"Income", "Ingreso_Familiar"}, 
				                                                                            {"Dt_Customer", "Fecha_Alta"}, 
				                                                                            {"Z_Revenue", "Ganancias_Campaña"}, 
				                                                                            {"Response", "Respuesta_Campaña"}, 
				                                                                            {"Complain", "Queja"}, 
				                                                                            {"Kidhome", "Hijos_Pequeños"}, 
				                                                                            {"Teenhome", "Hijos_Adolescentes"}, 
				                                                                            {"Recency", "Recencia"}, 
				                                                                            {"MntWines", "Gasto_Vinos"}, 
				                                                                            {"MntFruits", "Gasto_Frutas"}, 
				                                                                            {"MntMeatProducts", "Gasto_Carne"}, 
				                                                                            {"MntFishProducts", "Gasto_Pescado"}, 
				                                                                            {"MntSweetProducts", "Gasto_Dulces"}, 
				                                                                            {"Z_CostContact", "Costo_Contacto"}, 
				                                                                            {"MntGoldProds", "Gasto_Producto_Premium"}, 
				                                                                            {"NumDealsPurchases", "Compras_Descuento"}, 
				                                                                            {"NumWebPurchases", "Compras_Web"}, 
				                                                                            {"NumCatalogPurchases", "Compras_Catalogo"}, 
				                                                                            {"NumStorePurchases", "Compras_Tienda"}, 
				                                                                            {"NumWebVisitsMonth", "Visitas_Web_Mes"}, 
				                                                                            {"AcceptedCmp3", "Campaña_Aceptada_3"}, 
				                                                                            {"AcceptedCmp4", "Campaña_Aceptada_4"}, 
				                                                                            {"AcceptedCmp5", "Campaña_Aceptada_5"}, 
				                                                                            {"AcceptedCmp1", "Campaña_Aceptada_1"}, 
				                                                                            {"AcceptedCmp2", "Campaña_Aceptada_2"}}),
				
				// Eliminados 3 registros de personas (IDs: 1150, 7829, 11004) con edad mayor que 100 años. 
				    #"Añadida columna Age" = Table.AddColumn(#"Columnas con nombre cambiado", "Edad", each Date.Year(DateTimeZone.UtcNow()) - [Año_Nacimiento]),
				    #"Columna Edad reordenada" = Table.ReorderColumns(#"Añadida columna Age",{"ID", 
				                                                                            "Año_Nacimiento", 
				                                                                            "Edad", 
				                                                                            "Educación", 
				                                                                            "Estado_Civil", 
				                                                                            "Ingreso_Familiar", 
				                                                                            "Hijos_Pequeños", 
				                                                                            "Hijos_Adolescentes", 
				                                                                            "Fecha_Alta", 
				                                                                            "Recencia", 
				                                                                            "Gasto_Vinos", 
				                                                                            "Gasto_Frutas", 
				                                                                            "Gasto_Carne", 
				                                                                            "Gasto_Pescado", 
				                                                                            "Gasto_Dulces", 
				                                                                            "Gasto_Producto_Premium", 
				                                                                            "Compras_Descuento", 
				                                                                            "Compras_Web", 
				                                                                            "Compras_Catalogo", 
				                                                                            "Compras_Tienda", 
				                                                                            "Visitas_Web_Mes", 
				                                                                            "Campaña_Aceptada_3", 
				                                                                            "Campaña_Aceptada_4", 
				                                                                            "Campaña_Aceptada_5", 
				                                                                            "Campaña_Aceptada_1", 
				                                                                            "Campaña_Aceptada_2", 
				                                                                            "Queja", 
				                                                                            "Costo_Contacto", 
				                                                                            "Ganancias_Campaña", 
				                                                                            "Respuesta_Campaña"}),
				    #"Eliminados Mayores de 100 años" = Table.SelectRows(#"Columna Edad reordenada", each [Edad] < 100),
				
				// Añadir columna Tipo_Persona
				    #"Añadir columna Origen_Compra" = Table.AddColumn(#"Eliminados Mayores de 100 años", "Origen_Compra", each if [Compras_Descuento] = 0 and
				                                                                                                                [Compras_Web] = 0 and 
				                                                                                                                [Compras_Catalogo] = 0 and 
				                                                                                                                [Compras_Tienda] = 0 and 
				                                                                                                                [Visitas_Web_Mes] = 0 
				                                                                                                                then "Origen de Compra Desconocido" else "Origen de Compra Conocido")
				in
				    #"Añadir columna Origen_Compra"
				```

	annotation PBI_NavigationStepName = Navegación

	annotation PBI_ResultType = Table

